# Generated by Django 5.2.3 on 2025-06-21 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdd0d243-dc16-4b23-a296-84c662d7261e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
