name: Build and Deploy

on: 
  push:
    branches: [main]

jobs: 
  build_and_test:
    runs-on: windows-latest
    steps: 
      - name: Checkout mode
      uses: actions/checkout@v3

      - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
      - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
      -name: Run tests
      run: python manage.py test
  
  deploy:
    runs-on: windows-latest
    needs: [build_and_test]
    steps: 
      - name: echo hello world
      run: echo 'hello world'
